image:
  - Visual Studio 2019
  - Visual Studio 2022

branches:
  only:
    - main

platform:
  - x64

configuration:
  - Release
  - Debug

before_build:
  - mkdir build
  - cmake -S . -B build

build_script:
  - cmake --build build